### ISSUE TITLE
Kenan va passer bronze

### ISSUE THREAD

**Issue by Samsoum41** [KhaledELG/test#1]
Bonjour, Kenan va passer bronze, c'est grave de passer de Gold 1 à Bronze 1 en février quand meme

Cdt

**Comment by yac33dz** [comment]
Salut Samsoum41, à mon avis ça doit être un bug, j'ai épluché les data RIOT  c'est jamais arrivé. 
Est-ce qu'on a vérifié l'identité du joueur ? Est-ce que c'est un pas un bot/singe/dog derrière le compte ? 

Cdt,

**Comment by Samsoum41** [comment]
@riotgames est-ce que vous pouvez jeter un oeil à ce cas ? Le joueur exerce sur la midlane et il est déjà silver 4, l'heure est grave. Il joue un Ryze qui sent fortement des iep, vous ne pouvez pas le louper. Si c'est bien un bot/singe/dog derrière le compte, il faut vite s'en occuper. 

Cdt,

**Comment by AdelQasem** [comment]
C'est sûrement un compte acheté, je report dans le doute

**Comment by Samsoum41** [comment]
Ce joueur a cessé toute activité, il a compris qu'il ne pouvait pas remonter. Je pense qu'on peut fermer l'issue.
